name: 'Trigger CircleCI Pipeline'
description: 'Trigger pipelines on CircleCI for any event on GitHub.'
branding:
    icon: "check-circle"
    color: "green"
inputs:
  GHA_Meta:
    required: false
    description: 'An optional additional metadata parameter. Will be available on the CircleCI pipeline as GHA_Meta'
  env_workflow:
    required: false
    description: 'An optional environment parameter'
  cloudfront_url:
    required: false
    description: 'The Cloudfront URL'
  preview_bucket:
    required: false
    description: 'Where the built code should be placed'
runs:
  using: 'node12'
  main: 'dist/index.js'
