name: 'Trigger CircleCI Pipeline'
description: 'Trigger pipelines on CircleCI for any event on GitHub.'
branding:
    icon: "check-circle"
    color: "green"
inputs:
  GHA_Meta:
    required: false
    description: 'An optional additional metadata parameter. Will be available on the CircleCI pipeline as GHA_Meta'
  env-workflow:
    required: false
    description: 'An optional environment parameter'
  cloudfront-url:
    required: false
    description: 'The Cloudfront URL'
  cloudfront-id:
    required: false
    description: 'The Cloudfront ID for invalidations'
  preview-bucket:
    required: false
    description: 'Where the built code should be placed'
runs:
  using: 'node12'
  main: 'dist/index.js'
